- name: nginx install and run
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.server:
      name: nginx
      state: started
      enable: yes


      
    
  