 - name: variable from files
   hosts: local
   connection: local
   vars:
     - place.yaml 
   tasks:
   - name: Hello principal sir
     ansible.builtin.debug:
      msg: "Hello {{position}}, your start with carrer {{Experience}}, your from {{place}}"
