- name: condition demo
  hosts: local
  connection: local
  vars:
    NUMBER: 68
  tasks:
  - name: Number less than or equal to 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is less than to 100"
    when: Number > 100 