- name: condition demo
  hosts: local
  connection: local
  vars:
    NUMBER: 68
  tasks:
  - name: print Number less than or equal to 100
    ansible.builtin.debug:
      msg: "Given Number {{ NUMBER }} is less than to 100"
    when: NUMBER <= 100 

  - name: print Number greater than  100
    ansible.builtin.debug:
      msg: "Given Number {{ NUMBER }} is greater than to 100"
    when: NUMBER > 100 