- name: install control facts
  hosts: local
  connection: local
  tasks:
  - name: install if nginx in redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: install if nginx in  Debian 
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"
