- name: install package
  hosts: frontend
  become: yes
  tasks:
  - name: install package
    ansible.builtin.package:
     name: "{{ item }}"
     state: installed
    loop:
    - mysql
    - nginx
    - zip